module.exports = {
    'env': {
        'browser': true,
        'es6': true
    },
    'extends': 'eslint:recommended',
    'globals': {
        'Atomics': 'readonly',
        'SharedArrayBuffer': 'readonly'
    },
    'parserOptions': {
        'ecmaVersion': 2018,
        'sourceType': 'module'
    },
    'rules': {
        'no-var': ['warn'],
        'no-extra-parens': ['warn'],
        'no-template-curly-in-string': ['error'],
        'complexity': ['error'],
        'consistent-return': ['error'],
        'curly': ['error'],
        'default-case': ['error'],
        'dot-notation': ['error'],
        'eqeqeq': ['warn'],
        'max-classes-per-file': ['error', 1],
        'no-div-regex': ['error'],
        'no-else-return': ['error'],
        'no-empty-function': ['error'],
        'no-floating-decimal': ['error'],
        'no-implicit-coercion': ['error'],
        'no-implied-eval': ['error'],
        'no-invalid-this': ['error'],
        'no-lone-blocks': ['error'],
        'no-loop-func': ['error'],
        'no-multi-spaces': ['error'],
        'no-multi-str': ['error'],
        'no-new': ['error'],
        'no-param-reassign': ['error'],
        'no-proto': ['error'],
        'no-return-assign': ['error'],
        'no-script-url': ['error'],
        'no-useless-catch': ['error'],
        'no-useless-concat': ['error'],
        'no-useless-return': ['error'],
        'no-self-compare': ['error'],
        'no-throw-literal': ['error'],
        'no-unmodified-loop-condition': ['error'],
        'vars-on-top': ['warn'],
        'wrap-iife': ['error'],
        'yoda': ['error'],
        'no-void': ['error'],
        'init-declarations': ['error'],
        'no-shadow': ['error'],
        'no-shadow-restricted-names': ['error'],
        'no-undef-init': ['error'],
        'no-undefined': ['error'],
        'no-unused-vars': ['warn'],
        'no-use-before-define': ['error'],
        'array-bracket-newline': ['error'],
        'array-bracket-spacing': ['error'],
        'array-element-newline': ['error'],
        'block-spacing': ['error'],
        'brace-style': ['error'],
        'camelcase': ['error'],
        'comma-dangle': ['error'],
        'comma-spacing': ['error'],
        'comma-style': ['error'],
        'computed-property-spacing': ['error'],
        'consistent-this': ['error'],
        'func-call-spacing': ['error'],
        'func-names': ['error'],
        'func-style': ['error', 'declaration', {'allowArrowFunctions': true}],
        'indent': ['error'],
        'key-spacing': ['warn'],
        'keyword-spacing': ['warn'],
        'linebreak-style': ['error'],
        'lines-between-class-members': ['error'],
        'new-cap': ['error'],
        'new-parens': ['error'],
        'newline-per-chained-call': ['error'],
        'no-array-constructor': ['error'],
        'no-bitwise': ['error'],
        'no-continue': ['warn'],
        'no-lonely-if': ['warn'],
        'no-new-object': ['error'],
        'no-plusplus': ['error', {'allowForLoopAfterthoughts': true}],
        'no-tabs': ['error'],
        'no-trailing-spaces': ['error'],
        'no-underscore-dangle': ['error'],
        'no-unneeded-ternary': ['error'],
        'no-whitespace-before-property': ['error'],
        'semi-spacing': ['error', {'before': false, 'after': true}],
        'semi-style': ['error', 'last'],
        'space-before-blocks': ['error'],
        'switch-colon-spacing': ['error'],
        'wrap-regex': ['error'],
        'arrow-body-style': ['error'],
        'arrow-parens': ['error'],
        'arrow-spacing': ['error'],
        'no-confusing-arrow': ['error'],
        'no-duplicate-imports': ['error'],
        'no-useless-computed-key': ['error'],
        'no-useless-constructor': ['error'],
        'no-useless-rename': ['error'],
        'object-shorthand': ['error'],
        'prefer-const': ['error'],
        'prefer-numeric-literals': ['error'],
        'prefer-rest-params': ['warn'],
        'prefer-spread': ['warn'],
        'prefer-template': ['warn'],
        'rest-spread-spacing': ['error'],
        'sort-imports': ['error'],
        'template-curly-spacing': ['error'],
        'no-undef': ['warn'],
    }
}
